import { useEffect, useMemo, useState } from "react";
import { SERVICE_TYPES } from "../lib/constants";
import { createServiceOrder, fetchActiveTechnicians } from "../lib/api";
import { validateOrderForm } from "../lib/validation";
import type { CreatedOrderSummary, OrderFormErrors, OrderFormValues, TechnicianOption } from "../lib/types";
import { Field } from "./Field";
import { OrderSummaryCard } from "./OrderSummaryCard";

const emptyValues: OrderFormValues = {
  customer_name: "",
  phone: "",
  address: "",
  problem_description: "",
  service_type: "",
  quoted_price: "",
  assigned_technician_id: "",
  admin_notes: "",
};

export function OrderForm() {
  const [values, setValues] = useState<OrderFormValues>(emptyValues);
  const [errors, setErrors] = useState<OrderFormErrors>({});
  const [technicians, setTechnicians] = useState<TechnicianOption[]>([]);
  const [isLoadingTechnicians, setIsLoadingTechnicians] = useState(true);
  const [technicianError, setTechnicianError] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [createdOrder, setCreatedOrder] = useState<CreatedOrderSummary | null>(null);

  const noTechnicians = useMemo(
    () => !isLoadingTechnicians && !technicianError && technicians.length === 0,
    [isLoadingTechnicians, technicianError, technicians.length],
  );

  async function loadTechnicians() {
    setIsLoadingTechnicians(true);
    setTechnicianError(null);

    try {
      const data = await fetchActiveTechnicians();
      setTechnicians(data);
    } catch {
      setTechnicianError("We could not load active technicians from Supabase. Please check your connection and retry.");
    } finally {
      setIsLoadingTechnicians(false);
    }
  }

  useEffect(() => {
    void loadTechnicians();
  }, []);

  function updateField<K extends keyof OrderFormValues>(field: K, value: OrderFormValues[K]) {
    setValues((current) => ({ ...current, [field]: value }));
    setErrors((current) => {
      if (!current[field]) {
        return current;
      }

      const nextErrors = { ...current };
      delete nextErrors[field];
      return nextErrors;
    });
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitError(null);

    const nextErrors = validateOrderForm(values, technicians);
    setErrors(nextErrors);

    if (Object.keys(nextErrors).length > 0 || noTechnicians) {
      return;
    }

    setIsSubmitting(true);

    try {
      const created = await createServiceOrder(values);
      setCreatedOrder(created);
    } catch {
      setSubmitError("The order could not be created. Please review the details and try again.");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleCreateAnother() {
    setValues(emptyValues);
    setErrors({});
    setSubmitError(null);
    setCreatedOrder(null);
    await loadTechnicians();
  }

  if (createdOrder) {
    return <OrderSummaryCard order={createdOrder} onCreateAnother={() => void handleCreateAnother()} />;
  }

  return (
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
      <form onSubmit={handleSubmit} className="space-y-6">
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-panel">
          <div className="mb-6">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-700">Order Details</p>
            <h2 className="mt-2 text-xl font-semibold text-slate-900">Create a new service order</h2>
          </div>
          <Field
            htmlFor="order_no"
            label="Order No"
            hint="Generated by the Supabase RPC when the order is submitted."
          >
            <input
              id="order_no"
              value="Auto-generated on submit"
              readOnly
              className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-500"
            />
          </Field>
        </section>

        {submitError ? (
          <section className="rounded-3xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700 shadow-panel">
            {submitError}
          </section>
        ) : null}

        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-panel">
          <div className="grid gap-6 lg:grid-cols-2">
            <Field label="Customer Name" htmlFor="customer_name" required error={errors.customer_name}>
              <input
                id="customer_name"
                value={values.customer_name}
                onChange={(event) => updateField("customer_name", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
            <Field label="Phone" htmlFor="phone" required error={errors.phone}>
              <input
                id="phone"
                value={values.phone}
                onChange={(event) => updateField("phone", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
          </div>
          <div className="mt-6">
            <Field label="Address" htmlFor="address" required error={errors.address}>
              <textarea
                id="address"
                rows={4}
                value={values.address}
                onChange={(event) => updateField("address", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
          </div>
        </section>

        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-panel">
          <div className="mb-6">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-700">Service Information</p>
          </div>
          <div className="grid gap-6 lg:grid-cols-2">
            <Field label="Service Type" htmlFor="service_type" required error={errors.service_type}>
              <select
                id="service_type"
                value={values.service_type}
                onChange={(event) => updateField("service_type", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              >
                <option value="">Select a service</option>
                {SERVICE_TYPES.map((serviceType) => (
                  <option key={serviceType} value={serviceType}>
                    {serviceType}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="Quoted Price" htmlFor="quoted_price" required error={errors.quoted_price}>
              <input
                id="quoted_price"
                inputMode="decimal"
                value={values.quoted_price}
                onChange={(event) => updateField("quoted_price", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
          </div>
          <div className="mt-6">
            <Field
              label="Problem Description"
              htmlFor="problem_description"
              required
              error={errors.problem_description}
            >
              <textarea
                id="problem_description"
                rows={5}
                value={values.problem_description}
                onChange={(event) => updateField("problem_description", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
          </div>
        </section>

        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-panel">
          <div className="grid gap-6 lg:grid-cols-2">
            <Field
              label="Assigned Technician"
              htmlFor="assigned_technician_id"
              required
              error={errors.assigned_technician_id}
            >
              <select
                id="assigned_technician_id"
                value={values.assigned_technician_id}
                onChange={(event) => updateField("assigned_technician_id", event.target.value)}
                disabled={isLoadingTechnicians || noTechnicians}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100 disabled:bg-slate-100 disabled:text-slate-400"
              >
                <option value="">
                  {isLoadingTechnicians ? "Loading technicians..." : "Select technician"}
                </option>
                {technicians.map((technician) => (
                  <option key={technician.id} value={technician.id}>
                    {technician.name}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="Admin Notes" htmlFor="admin_notes" error={errors.admin_notes}>
              <textarea
                id="admin_notes"
                rows={4}
                value={values.admin_notes}
                onChange={(event) => updateField("admin_notes", event.target.value)}
                className="w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
              />
            </Field>
          </div>
        </section>

        <div className="flex flex-col gap-3 sm:flex-row">
          <button
            type="submit"
            disabled={isSubmitting || isLoadingTechnicians || noTechnicians}
            className="rounded-2xl bg-brand-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:bg-slate-300"
          >
            {isSubmitting ? "Submitting..." : "Create Service Order"}
          </button>
          <button
            type="button"
            onClick={() => {
              setValues(emptyValues);
              setErrors({});
              setSubmitError(null);
            }}
            className="rounded-2xl border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
          >
            Reset Form
          </button>
        </div>
      </form>

      <aside className="space-y-6">
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-panel">
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-brand-700">Workflow Status</p>
          <h2 className="mt-2 text-xl font-semibold text-slate-900">Module 1 scope</h2>
          <ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600">
            <li>Orders are created directly in the Assigned state.</li>
            <li>Technicians are loaded from Supabase to keep assignment data structured.</li>
            <li>Order numbers are generated server-side by the create_service_order RPC.</li>
          </ul>
        </section>

        {technicianError ? (
          <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-panel">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">Technician load failed</p>
            <p className="mt-3 text-sm leading-6 text-amber-800">{technicianError}</p>
            <button
              type="button"
              onClick={() => void loadTechnicians()}
              className="mt-4 rounded-2xl bg-amber-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-amber-600"
            >
              Retry loading technicians
            </button>
          </section>
        ) : null}

        {noTechnicians ? (
          <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-panel">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">No technicians available</p>
            <p className="mt-3 text-sm leading-6 text-amber-800">
              Seed the technicians table in Supabase with Ali, John, Bala, and Yusoff before creating orders.
            </p>
          </section>
        ) : null}
      </aside>
    </div>
  );
}
